export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_CHART_VALUES = 'SET_CHART_VALUES';
export const RESET_CHART_FETCHING = 'RESET_CHART_FETCHING';
export const SET_CHART_FETCHING = 'SET_CHART_FETCHING';
