export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_LINE_CHART_DATA = 'SET_LINE_CHART_DATA';
export const SET_LINE_CHART_FETCHING = 'SET_LINE_CHART_FETCHING';
export const RESET_LINE_CHART_FETCHING = 'RESET_LINE_CHART_FETCHING';
export const SET_GROUPED_PARAMETER = 'SET_GROUPED_PARAMETER';