export const SET_BUTTON_FETCHING = 'SET_BUTTON_FETCHING';
export const RESET_BUTTON_FETCHING = 'RESET_BUTTON_FETCHING';
export const SET_ACTIVITY_DATA_ITEMS = 'SET_ACTIVITY_DATA_ITEMS';
export const SET_ACTIVITY_CHART_DATA = 'SET_ACTIVITY_DATA_CHART_DATA';
