version: "3.1"

services:
  app:
    build: ./.docker/php-fpm
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  frontend:
    build:
      dockerfile: ./.docker/frontend/Dockerfile
      context: .
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./frontend:/app

  webserver:
    image: nginx:1.17.2-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.certs:/nginx/certs/
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - frontend
  
  redis:
    image: redis:5

  db:
    image: postgres
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
