version: "3.1"

services:
  app:
    build: ./.docker/php-fpm
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  webserver:
    image: nginx:1.17.2-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.certs:/nginx/certs/
  
  redis:
    image: redis:5

  db:
    image: postgres
    restart: always
    env_file:
      - .env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  beanstalk:
    image: schickling/beanstalkd:latest
