version: "3.1"

services:
  app:
    build: ./.docker/php-fpm
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

  frontend:
    image: node:12.7-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: "npm run serve" 

  webserver:
    image: nginx:1.17.2-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./.certs:/nginx/certs/
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=metrica
      - POSTGRES_USER=metrica
      - POSTGRES_PASSWORD=metrica
