version: "3.1"

services:
  webserver:
    ports:
      - "80:80"
      - "443:443"
  frontend:
    volumes:
      - ./frontend/public:/app
    command: [ 'hs', '-p', '3000' ]
  redis:
    volumes:
      - .redis:/data
  db:
    volumes:
      - .postgre:/var/lib/postgresql/data