export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_ACTIVE_BUTTON = 'SET_ACTIVE_BUTTON';
export const RESET_BUTTON_FETCHING = 'RESET_BUTTON_FETCHING';
export const SET_BUTTON_FETCHING = 'SET_BUTTON_FETCHING';
export const SET_LINE_CHART_DATA = 'SET_LINE_CHART_DATA';