export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_GROUPED_PARAMETER = 'SET_GROUPED_PARAMETER';
export const SET_ACTIVE_BUTTON = 'SET_ACTIVE_BUTTON';
export const RESET_BUTTON_FETCHING = 'RESET_BUTTON_FETCHING';
export const SET_BUTTON_FETCHING = 'SET_BUTTON_FETCHING';