export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_WIDGET_DATA = 'SET_WIDGET_DATA';
export const SET_DATA_FETCHING = 'SET_DATA_FETCHING';
export const RESET_DATA_FETCHING = 'RESET_DATA_FETCHING';