export const SET_CURRENT_WEBSITE = 'SET_CURRENT_WEBSITE';
export const UPDATE_CURRENT_WEBSITE = 'UPDATE_CURRENT_WEBSITE';
export const SET_WEBSITE_INFO = 'SET_WEBSITE_INFO';
export const RESET_CURRENT_WEBSITE = 'RESET_CURRENT_WEBSITE';
export const SET_FETCH_TRUE = 'SET_FETCH_TRUE';
export const RESET_WEBSITE_DATA = 'RESET_WEBSITE_DATA';