export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_IS_LOGGED_IN = 'SET_USER_IS_LOGGED_IN';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';