export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const USER_UPDATE = 'USER_UPDATE';
export const SET_TOKEN = 'SET_TOKEN';
