export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_ACTIVE_BUTTON = 'SET_ACTIVE_BUTTON';
export const RESET_BUTTON_FETCHING = 'RESET_BUTTON_FETCHING';
export const SET_BUTTON_FETCHING = 'SET_BUTTON_FETCHING';
export const SET_PAGE_VIEWS_TABLE_DATA = 'SET_PAGE_VIEWS_TABLE_DATA';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const RESET_IS_FETCHING = 'RESET_IS_FETCHING';
