export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_VISITS_DATA = 'SET_VISITS_DATA';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const RESET_IS_FETCHING = 'RESET_IS_FETCHING';
