export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_SELECTED_PARAMETER = 'SET_SELECTED_PARAMETER';
export const SET_GEO_LOCATION_ITEMS = 'SET_GEO_LOCATION_ITEMS';
export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const RESET_IS_FETCHING = 'RESET_IS_FETCHING';
