export const SET_SELECTED_PERIOD = 'SET_SELECTED_PERIOD';
export const SET_SELECTED_PARAMETER = 'SET_SELECTED_PARAMETER';
export const SET_GEO_LOCATION_ITEMS = 'SET_GEO_LOCATION_ITEMS';
export const RESET_GEO_LOCATION_ITEMS = 'RESET_GEO_LOCATION_ITEMS';
